#!/bin/bash
# Refresh Sources/MarktileApp/Resources/Engine from the repo's single sources.
#
# The Mac host must never carry its own copy of the editor. Everything under Engine/ is GENERATED
# and git-ignored; this script is the only thing allowed to write there, and build-app.sh runs it
# before every build. If the engine changes, the Mac app changes with it — there is no seam where
# the fourth surface could quietly drift from the other three.
set -euo pipefail
cd "$(dirname "$0")/.."          # hosts/mac
ROOT="$(cd ../.. && pwd)"        # repo root
ENGINE="Sources/MarktileApp/Resources/Engine"

# tile-core.js is itself emitted from packages/core/editor-core.js. Regenerate it rather than
# trusting whatever is checked in, so a stale emit can't ship inside the app.
echo "▸ regenerating tile-core.js from packages/core/editor-core.js"
bash "$ROOT/scripts/build-editor-core.sh"

mkdir -p "$ENGINE"
for f in \
  "dist/editor-core.js" \
  "packages/core/web-host.js" \
  "packages/core/obsidian-shim.js" \
  "Sortable.min.js" \
  "styles.css"
do
  src="$ROOT/$f"
  [ -f "$src" ] || { echo "✗ missing engine source: $f" >&2; exit 1; }
  cp "$src" "$ENGINE/$(basename "$f")"
done

# The .gitignore keeps the directory present (SwiftPM's .copy needs it to exist) while keeping the
# generated files out of the repo.
cat > "$ENGINE/.gitignore" <<'EOF'
# Generated by scripts/sync-engine.sh — do not commit, do not hand-edit.
*
!.gitignore
EOF

echo "✓ engine synced → $ENGINE"
ls -1 "$ENGINE" | grep -v '^\.gitignore$' | sed 's/^/  /'
