/*! coral drawer@0.1.1 +814ab5a — generated by dynamic-corals/build.mjs, do not edit */
(() => {
  // drawer-client.mjs
  (function() {
    var layers = document.querySelectorAll('[data-dynamic-coral="drawer"]');
    if (!layers.length) return;
    Array.prototype.forEach.call(layers, function(layer) {
      var panels = {};
      Array.prototype.forEach.call(layer.querySelectorAll("[data-drawer-panel]"), function(p) {
        panels[p.getAttribute("data-drawer-panel")] = p;
      });
      var openId = null, opener = null, onKey = null;
      function focusables(el) {
        return el.querySelectorAll('a[href],button,input,select,textarea,[tabindex]:not([tabindex="-1"])');
      }
      function release() {
        if (onKey) {
          document.removeEventListener("keydown", onKey, true);
          onKey = null;
        }
        if (opener) {
          try {
            opener.focus();
          } catch (e) {
          }
          opener = null;
        }
        openId = null;
      }
      function trap(id) {
        var panel = panels[id];
        if (!panel || openId === id) return;
        release();
        openId = id;
        var btn = panel.querySelector(".dc-drawer-close");
        if (btn) setTimeout(function() {
          try {
            btn.focus();
          } catch (e) {
          }
        }, 120);
        onKey = function(ev) {
          if (ev.key === "Escape") {
            ev.preventDefault();
            history.back();
            return;
          }
          if (ev.key !== "Tab") return;
          var f = focusables(panel);
          if (!f.length) return;
          var first = f[0], last = f[f.length - 1];
          if (ev.shiftKey && document.activeElement === first) {
            ev.preventDefault();
            last.focus();
          } else if (!ev.shiftKey && document.activeElement === last) {
            ev.preventDefault();
            first.focus();
          } else if (!panel.contains(document.activeElement)) {
            ev.preventDefault();
            first.focus();
          }
        };
        document.addEventListener("keydown", onKey, true);
      }
      document.addEventListener("click", function(e) {
        var t = e.target.closest && e.target.closest("[data-drawer]");
        if (t) opener = t;
      }, true);
      function sync() {
        var id = (location.hash || "").replace(/^#/, "");
        if (id && panels[id]) trap(id);
        else release();
      }
      window.addEventListener("hashchange", sync);
      sync();
    });
  })();
})();

(window.__coralVersions=window.__coralVersions||{})['drawer']='0.1.1';
