/*! coral sponsor@0.2.1 +dcde1ab — generated by dynamic-corals/build.mjs, do not edit */
(() => {
  // sponsor-core.mjs
  var UNMOUNTED_ATTR = "data-dc-sponsor-unmounted";
  var SPONSOR_PATH = "/api/v2/shop/sponsor";
  var SELECTOR = '[data-dynamic-coral="sponsor"]';
  var PREFIX = "dc-sponsor";
  var RETURN_PARAM = "dc_sponsor";
  var DEFAULT_AMOUNT_PARAM = "amount";
  var DEFAULT_MIN = "1";
  var DEFAULT_MAX = "1000000";
  var MAX_RAW_LEN = 32;
  var mountSeq = 0;
  var stylesInjected = false;
  function normalizeAmount(raw, opts) {
    const o = opts || {};
    if (raw === null || raw === void 0) return { ok: false, reason: "empty" };
    const s = String(raw).trim().replace(/[,\s]/g, "");
    if (!s) return { ok: false, reason: "empty" };
    if (s.length > MAX_RAW_LEN) return { ok: false, reason: "not_a_number" };
    if (!/^\d*(?:\.\d*)?$/.test(s) || s === ".") return { ok: false, reason: "not_a_number" };
    const dot = s.indexOf(".");
    const intPart = (dot === -1 ? s : s.slice(0, dot)).replace(/^0+(?=\d)/, "") || "0";
    const fracRaw = dot === -1 ? "" : s.slice(dot + 1);
    if (fracRaw.length > 2) return { ok: false, reason: "too_many_decimals" };
    const frac = fracRaw.replace(/0+$/, "");
    const amount = frac ? intPart + "." + frac : intPart;
    const hundredths = Number(intPart) * 100 + Number((fracRaw + "00").slice(0, 2));
    if (!Number.isFinite(hundredths)) return { ok: false, reason: "not_a_number" };
    if (hundredths === 0) return { ok: false, reason: "zero" };
    const min = boundHundredths(o.min, DEFAULT_MIN);
    const max = boundHundredths(o.max, DEFAULT_MAX);
    if (min !== null && hundredths < min) return { ok: false, reason: "below_min" };
    if (max !== null && hundredths > max) return { ok: false, reason: "above_max" };
    return { ok: true, amount, hundredths };
  }
  function boundHundredths(value, fallback) {
    for (const candidate of [value, fallback]) {
      if (candidate === null || candidate === void 0 || candidate === "") continue;
      const s = String(candidate).trim().replace(/[,\s]/g, "");
      if (s === "" || s === "." || !/^\d*(?:\.\d{0,2})?$/.test(s)) continue;
      const dot = s.indexOf(".");
      const intPart = dot === -1 ? s : s.slice(0, dot);
      const fracRaw = dot === -1 ? "" : s.slice(dot + 1);
      return Number(intPart || "0") * 100 + Number((fracRaw + "00").slice(0, 2));
    }
    return null;
  }
  function readPrefillAmount(search, param, bounds) {
    let raw;
    try {
      raw = new URLSearchParams(search || "").get(param || DEFAULT_AMOUNT_PARAM);
    } catch {
      return null;
    }
    if (raw === null) return null;
    const parsed = normalizeAmount(raw, bounds);
    return parsed.ok ? parsed.amount : null;
  }
  function parsePresets(raw, bounds) {
    if (!raw) return [];
    const out = [];
    for (const piece of String(raw).split("|").join(",").split(",")) {
      const parsed = normalizeAmount(piece, bounds);
      if (parsed.ok && !out.includes(parsed.amount)) out.push(parsed.amount);
    }
    return out;
  }
  function buildSponsorRequest(input) {
    return {
      guild_id: input.guildId,
      amount: input.amount,
      currency: input.currency,
      redirect_url: input.redirectUrl || void 0,
      client_request_ref: input.clientRequestRef
    };
  }
  function requestRefFor(refs, amount) {
    let ref = refs.get(amount);
    if (!ref) {
      ref = newClientRequestRef();
      refs.set(amount, ref);
    }
    return ref;
  }
  function newClientRequestRef() {
    if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
      return crypto.randomUUID();
    }
    const b = new Uint8Array(16);
    crypto.getRandomValues(b);
    b[6] = b[6] & 15 | 64;
    b[8] = b[8] & 63 | 128;
    const h = [];
    for (let i = 0; i < 16; i++) h.push(b[i].toString(16).padStart(2, "0"));
    return `${h[0]}${h[1]}${h[2]}${h[3]}-${h[4]}${h[5]}-${h[6]}${h[7]}-${h[8]}${h[9]}-${h[10]}${h[11]}${h[12]}${h[13]}${h[14]}${h[15]}`;
  }
  function apiBaseFrom(raw) {
    return (raw || "").trim().replace(/\/+$/, "");
  }
  function readConfig(el) {
    const attr = (name) => el.getAttribute(name);
    const currency = (attr("data-currency") || "TWD").trim().toUpperCase();
    const bounds = { min: attr("data-min") || DEFAULT_MIN, max: attr("data-max") || DEFAULT_MAX };
    return {
      guildId: attr("data-guild-id"),
      apiBase: apiBaseFrom(attr("data-api-base")),
      currency,
      currencyLabel: attr("data-currency-symbol") || currency,
      bounds,
      presets: parsePresets(attr("data-presets"), bounds),
      defaultAmount: attr("data-default-amount") || "",
      amountParam: attr("data-amount-param") || DEFAULT_AMOUNT_PARAM,
      title: attr("data-title") || "",
      note: attr("data-note") || "",
      labels: {
        amount: attr("data-amount-label") || "Amount",
        submit: attr("data-submit-label") || "Sponsor",
        invalid: attr("data-invalid-label") || "Enter an amount to sponsor.",
        error: attr("data-error-label") || "Could not start that just now \u2014 try again.",
        notActivated: attr("data-not-activated-label") || "This site hasn't turned on payments yet.",
        unconnected: attr("data-unconnected-label") || "Sponsoring is not set up on this site yet."
      }
    };
  }
  var SPONSOR_CSS = [
    `.${PREFIX}{display:block;padding:18px 20px;border-radius:var(--gd-radius,14px);background:var(--gd-soft,rgba(0,0,0,.04));border:1px solid var(--gd-border,rgba(0,0,0,.08));color:var(--gd-text,inherit)}`,
    `.${PREFIX}-title{font-size:1.1rem;font-weight:700;margin:0 0 6px;color:var(--gd-text,inherit)}`,
    `.${PREFIX}-note{margin:0 0 14px;opacity:.8;line-height:1.5}`,
    `.${PREFIX}-presets{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 12px}`,
    `.${PREFIX}-preset{padding:8px 14px;border-radius:999px;cursor:pointer;font:inherit;border:1px solid var(--gd-accent-deep,var(--gd-accent,#875fb6));background:var(--gd-surface,transparent);color:var(--gd-accent-deep,var(--gd-accent,#875fb6))}`,
    `.${PREFIX}-preset[aria-pressed="true"]{background:var(--gd-accent,#875fb6);color:var(--gd-surface,#fff)}`,
    `.${PREFIX}-row{display:flex;flex-wrap:wrap;align-items:stretch;gap:10px}`,
    `.${PREFIX}-field{display:flex;align-items:center;gap:6px;flex:1 1 160px;min-width:0;padding:0 12px;border-radius:var(--gd-radius,10px);border:1px solid var(--gd-border,rgba(0,0,0,.2));background:var(--gd-surface,#fff)}`,
    `.${PREFIX}-currency{opacity:.7;font-variant-numeric:tabular-nums}`,
    `.${PREFIX}-amount{flex:1 1 0%;min-width:0;border:0;background:transparent;color:inherit;font:inherit;font-size:1.1rem;padding:12px 0;font-variant-numeric:tabular-nums}`,
    `.${PREFIX}-amount:focus{outline:none}`,
    `.${PREFIX}-field:focus-within{outline:2px solid var(--gd-accent,#875fb6);outline-offset:2px}`,
    `.${PREFIX}-submit{padding:12px 22px;border:0;border-radius:var(--gd-radius,10px);cursor:pointer;font:inherit;font-weight:700;background:var(--gd-accent,#875fb6);color:var(--gd-surface,#fff)}`,
    `.${PREFIX}-submit[disabled]{opacity:.6;cursor:default}`,
    `.${PREFIX}-status{margin:10px 0 0;min-height:1.2em;color:var(--gd-text,inherit);opacity:.85}`,
    `.${PREFIX}-label{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}`
  ].join("");
  function injectStyles(doc) {
    if (stylesInjected) return;
    stylesInjected = true;
    const style = doc.createElement("style");
    style.setAttribute("data-dc", "sponsor");
    style.textContent = SPONSOR_CSS;
    doc.head.appendChild(style);
  }
  function make(doc, tag, className, text) {
    const node = doc.createElement(tag);
    if (className) node.className = className;
    if (text !== void 0 && text !== null && text !== "") node.textContent = text;
    return node;
  }
  function renderSponsor(doc, cfg) {
    const id = `${PREFIX}-amount-${++mountSeq}`;
    const root = make(doc, "form", PREFIX);
    root.setAttribute("novalidate", "novalidate");
    if (cfg.title) root.appendChild(make(doc, "div", `${PREFIX}-title`, cfg.title));
    if (cfg.note) root.appendChild(make(doc, "p", `${PREFIX}-note`, cfg.note));
    const presetNodes = [];
    if (cfg.presets.length) {
      const strip = make(doc, "div", `${PREFIX}-presets`);
      for (const amount of cfg.presets) {
        const b = make(doc, "button", `${PREFIX}-preset`, `${cfg.currencyLabel} ${amount}`);
        b.setAttribute("type", "button");
        b.setAttribute("data-amount", amount);
        b.setAttribute("aria-pressed", "false");
        strip.appendChild(b);
        presetNodes.push(b);
      }
      root.appendChild(strip);
    }
    const row = make(doc, "div", `${PREFIX}-row`);
    const field = make(doc, "div", `${PREFIX}-field`);
    const label = make(doc, "label", `${PREFIX}-label`, cfg.labels.amount);
    label.setAttribute("for", id);
    field.appendChild(label);
    field.appendChild(make(doc, "span", `${PREFIX}-currency`, cfg.currencyLabel));
    const input = make(doc, "input", `${PREFIX}-amount`);
    input.setAttribute("id", id);
    input.setAttribute("name", "amount");
    input.setAttribute("type", "text");
    input.setAttribute("inputmode", "decimal");
    input.setAttribute("autocomplete", "off");
    input.setAttribute("aria-describedby", `${id}-status`);
    field.appendChild(input);
    row.appendChild(field);
    const submit = make(doc, "button", `${PREFIX}-submit`, cfg.labels.submit);
    submit.setAttribute("type", "submit");
    row.appendChild(submit);
    root.appendChild(row);
    const status = make(doc, "p", `${PREFIX}-status`);
    status.setAttribute("id", `${id}-status`);
    status.setAttribute("role", "status");
    status.setAttribute("aria-live", "polite");
    root.appendChild(status);
    return { root, input, submit, status, presets: presetNodes };
  }
  function mountSponsor(el, deps) {
    const doc = deps && deps.document || document;
    const win = deps && deps.window || window;
    const send = deps && deps.fetch || ((url, init) => fetch(url, init));
    const cfg = readConfig(el);
    injectStyles(doc);
    const missing = !cfg.guildId ? "data-guild-id" : !cfg.apiBase ? "data-api-base" : "";
    if (missing) {
      el.setAttribute(UNMOUNTED_ATTR, missing);
      el.appendChild(make(doc, "p", `${PREFIX} ${PREFIX}-status`, cfg.labels.unconnected));
      return null;
    }
    const parts = renderSponsor(doc, cfg);
    el.appendChild(parts.root);
    const fromUrl = readPrefillAmount(safeSearch(win), cfg.amountParam, cfg.bounds);
    const fallback = normalizeAmount(cfg.defaultAmount, cfg.bounds);
    const prefill = fromUrl || (fallback.ok ? fallback.amount : "");
    if (prefill) parts.input.value = prefill;
    syncPresets(parts, prefill);
    for (const b of parts.presets) {
      b.addEventListener("click", () => {
        parts.input.value = b.getAttribute("data-amount");
        parts.status.textContent = "";
        syncPresets(parts, parts.input.value);
      });
    }
    parts.input.addEventListener("input", () => syncPresets(parts, parts.input.value));
    const refs = /* @__PURE__ */ new Map();
    let inFlight = false;
    parts.root.addEventListener("submit", (ev) => {
      if (ev && typeof ev.preventDefault === "function") ev.preventDefault();
      if (inFlight) return;
      const parsed = normalizeAmount(parts.input.value, cfg.bounds);
      if (!parsed.ok) {
        parts.status.textContent = cfg.labels.invalid;
        if (typeof parts.input.focus === "function") parts.input.focus();
        return;
      }
      parts.input.value = parsed.amount;
      syncPresets(parts, parsed.amount);
      inFlight = true;
      return startSponsorship(parsed.amount).then(() => {
        inFlight = false;
      });
    });
    function startSponsorship(amount) {
      const original = parts.submit.textContent;
      parts.submit.disabled = true;
      parts.submit.textContent = "\u2026";
      parts.status.textContent = "";
      const body = buildSponsorRequest({
        guildId: cfg.guildId,
        amount,
        currency: cfg.currency,
        redirectUrl: returnUrl(win),
        clientRequestRef: requestRefFor(refs, amount)
      });
      return Promise.resolve().then(() => send(cfg.apiBase + SPONSOR_PATH, {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "application/json" },
        body: JSON.stringify(body)
      })).then((res) => Promise.resolve(res.json()).catch(() => null).then((payload) => ({ res, payload }))).then(({ res, payload }) => {
        if (res.ok && payload && payload.url) {
          win.location.href = payload.url;
          return "navigated";
        }
        if (res.status === 403 && payload && payload.error === "checkout_module_not_activated") {
          return "not_activated";
        }
        return "error";
      }).catch(() => "error").then((outcome) => {
        if (outcome === "navigated") return;
        parts.submit.disabled = false;
        parts.submit.textContent = original;
        parts.status.textContent = outcome === "not_activated" ? cfg.labels.notActivated : cfg.labels.error;
      });
    }
    return parts;
  }
  function syncPresets(parts, amount) {
    for (const b of parts.presets) {
      b.setAttribute("aria-pressed", b.getAttribute("data-amount") === amount ? "true" : "false");
    }
  }
  function safeSearch(win) {
    try {
      return win.location.search || "";
    } catch {
      return "";
    }
  }
  function returnUrl(win) {
    try {
      return win.location.origin + win.location.pathname + `?${RETURN_PARAM}=done`;
    } catch {
      return void 0;
    }
  }

  // sponsor-client.mjs
  (function() {
    function mountAll() {
      var roots = document.querySelectorAll(SELECTOR);
      for (var i = 0; i < roots.length; i++) mountSponsor(roots[i]);
    }
    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", mountAll);
    } else {
      mountAll();
    }
  })();
})();

if (typeof window !== 'undefined') (window.__coralVersions=window.__coralVersions||{})['sponsor']='0.2.1';
