import {
	stripDonorHead, injectHead, replaceMain, matchShop,
	matchVerdictRule, normalizeVerdictPath,
	isSiteRelativePath, resolveInboxReturnPath,
} from './shop-function-template.js';
import { readFileSync } from 'node:fs';

let pass = 0, fail = 0;
const ok = (n, c) => { (c ? pass++ : fail++); console.log((c ? 'PASS' : 'FAIL'), '-', n); };

const templateSource = readFileSync(new URL('./shop-function-template.js', import.meta.url), 'utf8');
const fetchStart = templateSource.indexOf('async fetch(request, env, ctx)');
const cfgAt = templateSource.indexOf('const CFG = __SHOP_CONFIG__', fetchStart);
const canonicalAt = templateSource.indexOf('__CANONICAL_FETCH__', fetchStart);
const shopsAt = templateSource.indexOf('const shops =', fetchStart);
ok('canonical-host hook is first fetch action after baked config', fetchStart >= 0 && cfgAt < canonicalAt && canonicalAt < shopsAt);

// A shell like sitetile's built /shop page.
const SHELL = `<!doctype html><html lang="en"><head>` +
	`<meta charset="utf-8"><title>Shop — Northwind</title>` +
	`<meta name="description" content="OLD DESC">` +
	`<meta property="og:title" content="Shop"><meta property="og:image" content="/old-og.jpg">` +
	`<meta name="twitter:card" content="summary_large_image">` +
	`<link rel="canonical" href="https://example.com/shop">` +
	`</head><body>` +
	`<header class="rf-header">NAV</header>` +
	`<main class="rf-main reef-main"><section class="st-embed">GRID</section></main>` +
	`<footer class="rf-foot">FOOT</footer></body></html>`;

// stripDonorHead: donor's share metadata gone.
let s = stripDonorHead(SHELL);
ok('strips donor <title>', !s.includes('<title>Shop — Northwind</title>'));
ok('strips donor description', !s.includes('OLD DESC'));
ok('strips donor og:*', !s.includes('og:title') && !s.includes('/old-og.jpg'));
ok('strips donor twitter:*', !s.includes('twitter:card'));
ok('strips donor canonical', !s.includes('rel="canonical"'));
ok('keeps charset meta', s.includes('charset="utf-8"'));
ok('keeps header/nav + footer (shell chrome)', s.includes('rf-header') && s.includes('rf-foot'));

// injectHead: product meta lands before </head>.
const HEAD = `<title>RISO poster — NORTHWIND</title><meta property="og:image" content="/riso.jpg">`;
s = injectHead(s, HEAD);
ok('injects product head before </head>', s.includes('RISO poster — NORTHWIND') && s.indexOf('RISO poster') < s.indexOf('</head>'));

// replaceMain: <main> inner swapped, tag + chrome preserved.
s = replaceMain(s, '<div class="dc-pp">PRODUCT BODY</div>');
ok('main inner replaced', s.includes('PRODUCT BODY') && !s.includes('>GRID<'));
ok('main tag preserved', s.includes('<main class="rf-main reef-main">'));
ok('header/footer still present', s.includes('NAV') && s.includes('FOOT'));
ok('single <main> (no duplication)', (s.match(/<main\b/g) || []).length === 1);

// matchShop — routing (shops sorted longest-first, as the worker passes them).
const SHOPS = [{ shopPath: '/zh-tw/shop', labels: {} }, { shopPath: '/shop', labels: {} }];
ok('matches /shop/<slug>', matchShop('/shop/riso-poster', SHOPS)?.slug === 'riso-poster');
ok('matches /zh-tw/shop/<slug> (not /shop)', matchShop('/zh-tw/shop/x', SHOPS)?.shop.shopPath === '/zh-tw/shop');
ok('shop index /shop/ → no match', matchShop('/shop/', SHOPS) === null);
ok('bare /shop → no match', matchShop('/shop', SHOPS) === null);
ok('deep /shop/a/b → no match', matchShop('/shop/a/b', SHOPS) === null);
ok('unrelated /faq → no match', matchShop('/faq', SHOPS) === null);
ok('decodes slug', matchShop('/shop/a%20b', SHOPS)?.slug === 'a b');

// Verdict paths are generated by the renderer. Pages can hand the worker an equivalent spelling
// with an encoded separator, but only the separator is decoded here; malformed or unrelated
// percent escapes remain ordinary site paths.
const VERDICT = [{ match: 'exact', value: '/custom/2026/member-post' }];
for (const [alias, expected] of [
	['/custom/2026/member-post', '/custom/2026/member-post'],
	['/custom/2026/member-post/', '/custom/2026/member-post'],
	['/custom/2026/member-post/index.html', '/custom/2026/member-post'],
	['/custom%2F2026%2Fmember-post', '/custom/2026/member-post'],
	['/custom%2f2026%2fmember-post%2f', '/custom/2026/member-post'],
	['/custom%2F2026%2Fmember-post%2Findex.html', '/custom/2026/member-post'],
]) {
	ok(`normalizes ${alias}`, normalizeVerdictPath(alias) === expected);
	ok(`matches ${alias}`, matchVerdictRule(VERDICT, alias)?.value === expected);
}
ok('malformed encoded separator stays a near miss', matchVerdictRule(VERDICT, '/custom%2') === null);
ok('unrelated percent escape stays a near miss', matchVerdictRule(VERDICT, '/custom%252F2026%252Fmember-post') === null);

// isSiteRelativePath — the inbox forwarder's redirect-target guard.
ok('a real path is site-relative', isSiteRelativePath('/contact') === true);
ok('a path with a query/hash is still site-relative', isSiteRelativePath('/contact?x=1#y') === true);
ok('a network-path reference (//host) is rejected', isSiteRelativePath('//evil.example/x') === false);
ok('an absolute URL is rejected', isSiteRelativePath('https://evil.example/x') === false);
ok('a bare host with no leading slash is rejected', isSiteRelativePath('evil.example/x') === false);
ok('empty string is rejected', isSiteRelativePath('') === false);
ok('undefined is rejected', isSiteRelativePath(undefined) === false);

// resolveInboxReturnPath — return_to (if site-relative) → same-origin Referer's path → '/'.
const ORIGIN = 'https://s.example';
ok('return_to wins when site-relative', resolveInboxReturnPath('/contact', 'https://s.example/other', ORIGIN) === '/contact');
ok('falls back to the same-origin Referer\'s path when return_to is absent', resolveInboxReturnPath(undefined, 'https://s.example/other?x=1', ORIGIN) === '/other?x=1');
ok('falls back to the same-origin Referer when return_to is foreign', resolveInboxReturnPath('https://evil.example/x', 'https://s.example/other', ORIGIN) === '/other');
ok('falls back to / when neither return_to nor Referer is usable', resolveInboxReturnPath('//evil.example/x', 'https://evil.example/y', ORIGIN) === '/');
ok('falls back to / when both are entirely absent', resolveInboxReturnPath(undefined, '', ORIGIN) === '/');

console.log(`\n=== ${pass}/${pass + fail} PASS ===`);
process.exit(fail ? 1 : 0);
