#!/bin/bash
# tugtile-w web preview build.
# board-core.js is generated by scripts/build-board-core.sh and vendor/editor-core.js is copied
# from this repo's dist/ — both local, both checked by scripts/test.sh's freshness gate.
#
# 🩸 These four lines used to say both were "VENDORED from CVERInc/tile via scripts/fetch-tile.sh",
# which was true when this surface lived in the private lab and false the moment it graduated:
# that script is in the OTHER repo. A build script describing somebody else's mechanism is how an
# artifact ends up with no owner.
set -e
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"

# Real tugtile stylesheet, verbatim (same CSS, not a re-implementation).
cp "$ROOT/styles.css" "$ROOT/hosts/web/tugtile/tugtile.css"
echo "copied tugtile.css (verbatim styles.css)"

# SortableJS — the same drag engine, so cards/lanes are draggable ("tug").
cp "$ROOT/Sortable.min.js" "$ROOT/hosts/web/tugtile/Sortable.min.js"
echo "copied Sortable.min.js"
# 🩸 THE BOARD MODEL, AND IT WAS NEVER COPIED (2026-09-06). index.html's first import is
# `./board-core.js`; scripts/build-board-core.sh writes it to packages/tugtile/ and nothing copied it
# here, so a clean checkout served a host whose module never evaluated: an empty board, no handlers.
# Not a symlink and not an import rewrite: this directory is meant to be servable on its own.
[ -f "$ROOT/packages/tugtile/board-core.js" ] || { echo "board-core.js is missing — run scripts/build-board-core.sh first" >&2; exit 1; }
cp "$ROOT/packages/tugtile/board-core.js" "$ROOT/hosts/web/tugtile/board-core.js"
echo "copied board-core.js (from packages/tugtile/)"

# i18n — the same locale JSON, so strings match exactly.
mkdir -p "$ROOT/hosts/web/tugtile/i18n"
cp "$ROOT/i18n/"*.json "$ROOT/hosts/web/tugtile/i18n/"
echo "copied i18n/*.json"


# 🔴 The engine is COPIED from this repo, not fetched from it. Until these surfaces graduated they
# lived in the private lab and pulled the engine across a repo boundary via fetch-tile.sh — which
# is why three surfaces once carried two different builds while all of them said "latest". They are
# in the same repo as their engine now, so the copy is local, unconditional, and checked by
# scripts/test.sh's "generated artifacts in sync" gate. There is no version left to disagree about.
mkdir -p "$ROOT/hosts/web/tugtile/vendor"
cp "$ROOT/dist/editor-core.js" "$ROOT/hosts/web/tugtile/vendor/editor-core.js"
echo "copied vendor/editor-core.js (from this repo's dist/)"

echo "build complete — board-core.js via scripts/build-board-core.sh; vendor/editor-core.js copied from tile-core/;"
echo "  obsidian-shim.js, host.js, icons.js are committed static glue."
