/*! coral repo-facts@0.1.0 +e6a8448 — generated by dynamic-corals/build.mjs, do not edit */
(() => {
  // repo-facts-core.mjs
  var SELECTOR = '[data-dynamic-coral="repo-facts"]';
  var PATH = "/v0/repo-facts";
  var TIMEOUT_MS = 3e3;
  var DIAGNOSTICS = "__coralDiagnostics";
  var MARK = "data-dc-repo-facts";
  var DAY = 864e5;
  var UPDATED = { en: (x) => `Updated ${x}`, zh: (x) => `${x} \u66F4\u65B0`, ja: (x) => `${x} \u66F4\u65B0`, ko: (x) => `\uC5C5\uB370\uC774\uD2B8 \uB0A0\uC9DC: ${x}` };
  var ARCHIVED = { en: "Archived", zh: "\u5DF2\u5C01\u5B58", ja: "\u30A2\u30FC\u30AB\u30A4\u30D6\u6E08\u307F", ko: "\uBCF4\uAD00\uB428" };
  var langOf = (tag) => {
    const p = String(tag || "").split("-")[0].toLowerCase();
    return UPDATED[p] ? p : "en";
  };
  function relative(day, now, tag) {
    if (!/^\d{4}-\d\d-\d\d$/.test(day) || Number.isNaN(Date.parse(day))) return "";
    const days = Math.max(0, Math.round((Math.floor(now / DAY) * DAY - Date.parse(day)) / DAY));
    const [n, unit] = days < 30 ? [days, "day"] : days < 365 ? [Math.floor(days / 30), "month"] : [Math.floor(days / 365), "year"];
    const lang = langOf(tag);
    let fmt;
    try {
      fmt = new Intl.RelativeTimeFormat(lang === "en" ? "en" : tag, { numeric: "auto" });
    } catch {
      fmt = new Intl.RelativeTimeFormat(lang, { numeric: "auto" });
    }
    return fmt.format(-n, unit);
  }
  function repoOf(href, owner) {
    try {
      const u = new URL(href), m = /^\/([\w.-]+)\/([\w.-]+?)(?:\.git)?\/?$/.exec(u.pathname);
      return u.hostname === "github.com" && m && m[1].toLowerCase() === owner.toLowerCase() ? m[2].toLowerCase() : "";
    } catch {
      return "";
    }
  }
  function fillCards(doc, data, owner, tag, now) {
    const lang = langOf(tag);
    for (const card of doc.querySelectorAll(".st-item")) {
      const name = [...card.querySelectorAll("a[href]")].map((a) => repoOf(a.href, owner)).find(Boolean);
      const f = name && Object.hasOwn(data, name) && data[name];
      if (!f || typeof f !== "object") continue;
      const span = card.querySelector(".st-item-updated"), phrase = relative(f.pushed_at, now, tag);
      if (span && phrase) {
        span.textContent = UPDATED[lang](phrase);
        span.setAttribute(MARK, name);
      }
      const head = card.querySelector(".st-item-head");
      const has = [...card.querySelectorAll(".st-item-badge")].some((b) => Object.values(ARCHIVED).includes(b.textContent.trim()));
      if (f.archived === true && head && !has) {
        let box = card.querySelector(".st-item-badges");
        if (!box) {
          box = doc.createElement("span");
          box.className = "st-item-badges";
          head.appendChild(box);
        }
        const badge = doc.createElement("span");
        badge.className = "st-item-badge";
        badge.setAttribute(MARK, name);
        badge.textContent = ARCHIVED[lang];
        box.appendChild(badge);
      }
    }
    return [...doc.querySelectorAll(".st-item")].filter((c) => c.querySelector(`[${MARK}]`)).length;
  }
  async function mountRepoFacts(root, opts = {}) {
    const all = window[DIAGNOSTICS] ||= {};
    try {
      const base = /^https:\/\/[^/]+/.exec(root.getAttribute("data-api-base") || "")[0];
      const owner = root.getAttribute("data-owner") || "";
      if (!/^[\w.-]{1,100}$/.test(owner)) throw 0;
      const r = await fetch(
        `${base}${PATH}?owner=${owner}`,
        { signal: AbortSignal.timeout(opts.timeoutMs || TIMEOUT_MS), credentials: "omit", redirect: "error" }
      );
      if (!r.ok) throw 0;
      const data = await r.json();
      if (!data || typeof data !== "object" || Array.isArray(data)) throw 0;
      const tag = root.getAttribute("data-locale") || document.documentElement.lang || "en";
      return all["repo-facts"] = { filled: fillCards(document, data, owner, tag, opts.now || Date.now()) };
    } catch {
      return all["repo-facts"] ||= { error: 1 };
    }
  }

  // repo-facts-client.mjs
  var mountAll = () => document.querySelectorAll(SELECTOR).forEach((root) => mountRepoFacts(root));
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", mountAll);
  else mountAll();
})();

if (typeof window !== 'undefined') (window.__coralVersions=window.__coralVersions||{})['repo-facts']='0.1.0';
