/*! coral repo-facts@0.1.0 +971966b — generated by dynamic-corals/build.mjs, do not edit */
(() => {
  // repo-facts-fields.mjs
  var REPO = /^[\w.-]{1,100}\/[\w.-]{1,100}$/;
  var text = (re) => (v) => typeof v === "string" && re.test(v);
  var day = (v) => typeof v === "string" && new Date(v).toJSON()?.slice(0, 10) === v;
  var FIELDS = {
    tag: text(/^(?=.{1,40}$)v?\d+(\.\d+){1,3}([-.+][0-9A-Za-z.-]+)?$/),
    releasedAt: day,
    pushedAt: day,
    license: text(/^[A-Za-z0-9.+-]{1,40}$/),
    archived: (v) => typeof v === "boolean",
    fullName: text(REPO)
  };

  // repo-facts-core.mjs
  var SELECTOR = '[data-dynamic-coral="repo-facts"]';
  var PATH = "/v0/repo-facts";
  var MAX_REPOS = 30;
  var TIMEOUT_MS = 3e3;
  var DIAGNOSTICS = "__coralDiagnostics";
  var MARK = "data-dc-repo-facts";
  var HOSTS = { github: "github.com" };
  var ARCHIVED = { zh: "\u5DF2\u5C01\u5B58", ja: "\u30A2\u30FC\u30AB\u30A4\u30D6\u6E08\u307F", ko: "\uBCF4\uAD00\uB428" };
  function repoOf(href, host) {
    try {
      const u = new URL(href);
      const name = u.pathname.replace(/^\/+|\/+$/g, "").replace(/\.git$/, "");
      return u.hostname === host && REPO.test(name) ? name : "";
    } catch {
      return "";
    }
  }
  function findCards(scope, host) {
    const cards = /* @__PURE__ */ new Map();
    for (const a of scope.querySelectorAll("a[href]")) {
      const name = repoOf(a.href, host), card = name && a.closest(".st-item");
      if (card && !cards.has(card) && new Set(cards.values()).add(name).size <= MAX_REPOS) cards.set(card, name);
    }
    return cards;
  }
  function checkResponse(data, names) {
    const out = {};
    for (const n of names) {
      const f = Object.hasOwn(data, n) && data[n];
      out[n] = f && typeof f === "object" && Object.keys(FIELDS).every((k) => f[k] == null || FIELDS[k](f[k])) ? f : {};
    }
    return out;
  }
  function fillCards(cards, facts, lang) {
    const renamed = {};
    for (const [card, name] of cards) {
      const f = facts[name], slot = card.querySelector(".st-item-meta-left");
      if (!slot || card.querySelector(`[${MARK}]`)) continue;
      if (f.fullName && f.fullName.toLowerCase() !== name.toLowerCase()) renamed[name] = f.fullName;
      const el = document.createElement("span");
      el.className = "st-item-updated";
      el.setAttribute(MARK, name);
      if (f.archived) {
        const badge = document.createElement("span");
        badge.className = "st-item-badge";
        badge.textContent = ARCHIVED[lang.split("-")[0].toLowerCase()] || "Archived";
        el.append(badge);
      } else if (f.tag && f.releasedAt) {
        const day2 = (l) => new Date(f.releasedAt).toLocaleDateString(l, { dateStyle: "long", timeZone: "UTC" });
        const time = document.createElement("time");
        time.dateTime = f.releasedAt;
        try {
          time.textContent = day2(lang);
        } catch {
          time.textContent = day2("en");
        }
        el.append(f.tag + " \xB7 ", time);
      } else continue;
      slot.insertBefore(el, slot.querySelector(".st-item-gh"));
    }
    return renamed;
  }
  async function mountRepoFacts(root, timeoutMs = TIMEOUT_MS) {
    const all = window[DIAGNOSTICS] ||= {};
    const attr = (k) => root.getAttribute(k) || "";
    try {
      const base = /^https:\/\/[^/]+/.exec(attr("data-api-base"))[0];
      const scope = attr("data-scope") ? document.querySelector(attr("data-scope")) : document;
      const cards = findCards(scope, HOSTS[attr("data-forge") || "github"]);
      const names = [...new Set(cards.values())].sort();
      if (!names.length) throw 0;
      const r = await fetch(
        `${base}${PATH}?repos=${names}`,
        { signal: AbortSignal.timeout(timeoutMs), credentials: "omit", redirect: "error" }
      );
      if (!r.ok) throw 0;
      const renamed = fillCards(cards, checkResponse(await r.json(), names), document.documentElement.lang || "en");
      return all["repo-facts"] = {
        filled: document.querySelectorAll(`[${MARK}]`).length,
        renamed: { ...all["repo-facts"]?.renamed, ...renamed }
      };
    } catch {
      return all["repo-facts"] ||= { error: 1 };
    }
  }

  // repo-facts-client.mjs
  var mountAll = () => document.querySelectorAll(SELECTOR).forEach((root) => mountRepoFacts(root));
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", mountAll);
  else mountAll();
})();

if (typeof window !== 'undefined') (window.__coralVersions=window.__coralVersions||{})['repo-facts']='0.1.0';
